---
title: "GCTD Report Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(haven)
library(plyr)#append data set with different number of column  
library(tidyverse)
library(dplyr)
library(lubridate)#date & time
library(highcharter)
library(plotly)
library(DT)#data table
library(stringr)#string replacement

```

```{r read}
#Import Employee Data
# 8/31
employee <- read_dta("Employees Questionnaire.dta")
employee0 <- read_dta("Employees Questionnaire0.dta")
employee <- rbind.fill(employee, employee0)
employee <- as_factor(employee)

employee$submissiondate <- as_date(employee$submissiondate)

#Import Profile data
profile <- read_dta("Profile Questionnaire.dta")
profile0 <- read_dta("Profile Questionnaire0.dta")
profile <- rbind.fill(profile, profile0)
profile <- as_factor(profile)
profile$submissiondate <- as_date(profile$submissiondate)

#Import Client Data
client <- read_dta("Clients Questionnaire.dta")
client0 <- read_dta("Clients Questionnaire0.dta")
client <- rbind.fill(client, client0)
client <- as_factor(client)
client$submissiondate <- as_date(client$submissiondate)

#Import expected table
expected_table <- read_csv("Table Expected.csv")
```

HOME
=====================================

Row
-----------------------------------------------------------------------

### EMOPLOYEE

```{r}
num_emp <- nrow(employee)
valueBox(num_emp, icon = "fa-bar-chart")
```

### PROFILE

```{r}
num_profile <- nrow(profile)
valueBox(num_profile, icon = "fa-bar-chart")

```

### CLIENT

```{r}
num_client <- nrow(client)
valueBox(num_client,icon = "fa-bar-chart")

```

### TOTAL

```{r}
total_tool <- sum(num_emp,num_profile, num_client)

valueBox(total_tool,icon = "fa-pencil", color = "orange")

```

### LAST UPDATED AT:  
```{r}
updated_time <- Sys.Date()

valueBox(updated_time,icon = "fa-clock", color = "white")

```

```{r}
tool_type <- c("Employee", "Profile", "Client")
synced_tool <- c(num_emp,num_profile,num_client)

```

```{r Employee }
Asnake_emp <- employee %>% filter(supervisor=="Asnake Getu") %>% nrow()
Addis_emp <- employee %>% filter(supervisor=="Addis Mengistu") %>% nrow()
Selamu_emp <- employee %>% filter(supervisor=="Selamu Bulado") %>% nrow()
Solomon_emp <- employee %>% filter(supervisor=="Solomon Genore") %>% nrow()
Natnael_emp <- employee %>% filter(supervisor=="Natnael Shewanes") %>% nrow()
Hiwot_emp <- employee %>% filter(supervisor=="Hiwot Zelalem") %>% nrow()
Besu_emp <- employee %>% filter(supervisor=="Besufikad Birhanu") %>% nrow()
Habtamu_emp <- employee %>% filter(supervisor=="Habtamu Ayele") %>% nrow()
Sisay_emp <- employee %>% filter(supervisor=="Sisay addis") %>% nrow()
Bekalu_emp <- employee %>% filter(supervisor=="Bekalu dibaba") %>% nrow()
Henok_emp <- employee %>% filter(supervisor=="Henok Ayele") %>% nrow()
Belachew_emp <- employee %>% filter(supervisor=="Belachew Mamuye") %>% nrow()
```

```{r Profile }
Asnake_pro <- profile %>% filter(supervisor=="Asnake Getu") %>% nrow()
Addis_pro <- profile %>% filter(supervisor=="Addis Mengistu") %>% nrow()
Selamu_pro <- profile %>% filter(supervisor=="Selamu Bulado") %>% nrow()
Solomon_pro <- profile %>% filter(supervisor=="Solomon Genore") %>% nrow()
Natnael_pro <- profile %>% filter(supervisor=="Natnael Shewanes") %>% nrow()
Hiwot_pro <- profile %>% filter(supervisor=="Hiwot Zelalem") %>% nrow()
Besu_pro <- profile %>% filter(supervisor=="Besufikad Birhanu") %>% nrow()
Habtamu_pro <- profile %>% filter(supervisor=="Habtamu Ayele") %>% nrow()
Sisay_pro <- profile %>% filter(supervisor=="Sisay addis") %>% nrow()
Bekalu_pro <- profile%>% filter(supervisor=="Bekalu dibaba") %>% nrow()
Henok_pro <- profile%>% filter(supervisor=="Henok Ayele") %>% nrow()
Belachew_pro <- profile%>% filter(supervisor=="Belachew Mamuye") %>% nrow()
```

```{r Client}
Asnake_cli <- client %>% filter(supervisor=="Asnake Getu") %>% nrow()
Addis_cli <- client %>% filter(supervisor=="Addis Mengistu") %>% nrow()
Selamu_cli <- client %>% filter(supervisor=="Selamu Bulado") %>% nrow()
Solomon_cli <- client %>% filter(supervisor=="Solomon Genore") %>% nrow()
Natnael_cli <- client %>% filter(supervisor=="Natnael Shewanes") %>% nrow()
Hiwot_cli <- client %>% filter(supervisor=="Hiwot Zelalem") %>% nrow()
Besu_cli <- client %>% filter(supervisor=="Besufikad Birhanu") %>% nrow()
Habtamu_cli <- client %>% filter(supervisor=="Habtamu Ayele") %>% nrow()
Sisay_cli <- client %>% filter(supervisor=="Sisay addis") %>% nrow()
Bekalu_cli <- client%>% filter(supervisor=="Bekalu dibaba") %>% nrow()
Henok_cli <- client%>% filter(supervisor=="Henok Ayele") %>% nrow()
Belachew_cli <- client%>% filter(supervisor=="Belachew Mamuye") %>% nrow()
```

Column {.tabset}
-----------------------------------------------------------------------
### EMPLOYEE DATA TRAIND

```{r}
employee %>% select('submissiondate', 'supervisor') %>% 
  arrange(submissiondate) %>% 
  count( submissiondate,supervisor) %>% 
  hchart('spline', hcaes(x = 'submissiondate', y = 'n', group = "supervisor"))

```


### CLIENT DATA TRAIND
```{r}
client %>% select('submissiondate', 'supervisor') %>% 
  arrange(submissiondate) %>% 
  count( submissiondate,supervisor) %>% 
  hchart('spline', hcaes(x = 'submissiondate', y = 'n', group = "supervisor"))

```


### PROFILE DATA TRAIND
```{r}
profile %>% select('submissiondate', 'supervisor') %>% 
  arrange(submissiondate) %>% 
  count( submissiondate,supervisor) %>% 
  hchart('spline', hcaes(x = 'submissiondate', y = 'n', group = "supervisor"))

```


Column 
-----------------------------------------------------------------------

### SUPERVISOR BY QUESTIONNAIRE TYPE

```{r}
sup_name <- c("Asnake", "Addis", "Selamu", "Solomon", "Natnael", "Hiwot", "Besufikad", "Habtamu", "Sisay", "Bekalu", "Henok", "Belachew")
sup_emp <- c(Asnake_emp, Addis_emp, Selamu_emp, Solomon_emp, Natnael_emp, Hiwot_emp, Besu_emp, Habtamu_emp, Sisay_emp, Bekalu_emp, Henok_emp, Belachew_emp)
sup_pro <- c(Asnake_pro, Addis_pro, Selamu_pro, Solomon_pro, Natnael_pro, Hiwot_pro, Besu_pro, Habtamu_pro, Sisay_pro, Bekalu_pro, Henok_pro, Belachew_pro)
sup_cli <- c(Asnake_cli, Addis_cli, Selamu_cli, Solomon_cli, Natnael_cli, Hiwot_cli, Besu_cli, Habtamu_cli, Sisay_cli, Bekalu_cli, Henok_cli, Belachew_cli)

data_sup <- data.frame(sup_name, sup_emp, sup_pro, sup_cli)
data_sup <- data_sup %>% arrange(sup_emp)
#to arrange
data_sup$sup_name<- factor(data_sup$sup_name, levels=data_sup[["sup_name"]])

#plot fig
fig1 <- data_sup %>% plot_ly()
fig1 <- fig1 %>% add_trace(x = ~sup_name, y = ~sup_emp, type = 'bar',  name = 'Employee', marker = list(color = '#0AA1DD'))
fig1 <- fig1 %>% add_trace(x = ~sup_name, y = ~sup_cli, type = 'bar', name = 'Client', marker = list(color = '#006E7F'))
fig1 <- fig1 %>% add_trace(x = ~sup_name, y = ~sup_pro, type = 'bar', name = 'Profile', marker = list(color = '#79DAE8'))
fig1 <- fig1 %>% layout(xaxis = list(title = 'SUPERVISOR'), barmode = 'group')          
fig1 <- fig1 %>% layout(yaxis = list(title = 'n'), barmode = 'group')

fig1

```



### TOTAL SYNCED DATA BY REGION 
```{r }
employee %>% 
  dplyr::count(region) %>%
  arrange(-n) %>% 
  hchart('bar', hcaes(x = 'region', y = 'n'))
```

### TOTAL SYNCED DATA BY QUESTIONNAIRE TYPE

```{r}
tool_type <- c("Employee", "Profile", "Client")
synced_tool <- c(num_emp, num_profile, num_client)


fig <- plot_ly(type='pie', labels= ~tool_type, values= ~synced_tool,
               textinfo='label+percent',
               insidetextorientation='radial',
               marker = list(colors = c('#646FD4', '#DBDFFD', "#9BA3EB"))
               
               )
fig

```





ADMNIST. LEVEL
=====================================
```{r expected}
# Expected data
supervisor <- c("Addis Mengistu",	"Asnake Getu",	"Hiwot Zelalem",	"Natnael Shewanes",	"Selamu Bulado","Solomon Genore", "Besufikad Birhanu", "Habtamu Ayele", "Sisay addis", "Bekalu dibaba", "Henok Ayele", "Belachew Mamuye")
emp_fed_exp <- c(0,	0, 62.5, 62.5,	0,	0, 0, 0, 0, 0, 0, 0)
emp_reg_exp <- c(0,	0, 52.5, 52.5, 210, 105, 105, 105, 105, 105, 315, 105)
emp_zone_exp <- c(80,	0, 100, 100, 80, 120, 80, 120, 80, 80, 80, 80)
emp_woreda_exp <- c(160, 160, 80, 80, 224, 256, 224, 192,192, 192, 224,96)
client_exp <- c(240, 240, 120, 120, 336, 384, 336, 288, 288, 288, 336, 144)
profile_exp <- c(56, 40, 63, 63, 114,109, 93, 93, 85, 85, 199, 61)

df_expected <- data.frame(supervisor, emp_fed_exp, emp_reg_exp, emp_zone_exp, emp_woreda_exp, client_exp, profile_exp)

# Actual data emp
emp_fed_act <- employee %>% filter(org_level == "Federal") %>% 
  group_by(supervisor) %>% dplyr::summarise(count_fed_emp = n()) %>%
  arrange(count_fed_emp)

emp_reg_act <- employee %>% filter(org_level == "Regional") %>% 
  group_by(supervisor) %>% dplyr::summarise(count_reg_emp = n()) %>% 
  arrange(count_reg_emp)

emp_zone_act <- employee %>% filter(org_level == "Zonal") %>% 
  group_by(supervisor) %>% dplyr::summarise(count_zone_emp = n()) %>% 
  arrange(count_zone_emp)

emp_woreda_act <- employee %>% filter(org_level == "Woreda") %>% 
  group_by(supervisor) %>% dplyr::summarise(count_woreda_emp = n()) %>% 
  arrange(count_woreda_emp)

# Actual data client
client_act <- client %>% group_by(supervisor) %>% dplyr::summarise(count_client = n()) %>% arrange(count_client)

# Actual data profile
profile_act <- profile %>% group_by(supervisor) %>% dplyr::summarise(count_profile = n()) %>% arrange(count_profile)

# change to factor
emp_fed_act$supervisor<- factor(emp_fed_act$supervisor, levels=emp_fed_act[["supervisor"]])
emp_reg_act$supervisor<- factor(emp_reg_act$supervisor, levels=emp_reg_act[["supervisor"]])
emp_zone_act$supervisor<- factor(emp_zone_act$supervisor, levels=emp_zone_act[["supervisor"]])
emp_woreda_act$supervisor<- factor(emp_woreda_act$supervisor, levels=emp_woreda_act[["supervisor"]])
client_act$supervisor<- factor(client_act$supervisor, levels=client_act[["supervisor"]])
profile_act$supervisor<- factor(profile_act$supervisor, levels=profile_act[["supervisor"]])

# ----Merge each type of questionnaire by actual and expected----#
df_merge_fed <- inner_join(x = emp_fed_act, y = df_expected, by="supervisor")
#rename sup name
df_merge_fed <- df_merge_fed %>% mutate(supervisor = str_replace(supervisor,"Addis Mengistu", "Addis"), supervisor = str_replace(supervisor, "Asnake Getu", "Asnake"),
supervisor = str_replace(supervisor, "Hiwot Zelalem", "Hiwot"), supervisor = str_replace(supervisor, "Natnael Shewanes", "Natnael"),
supervisor = str_replace(supervisor, "Selamu Bulado", "Selamu"), supervisor = str_replace(supervisor, "Solomon Genore", "Solomon"), 
supervisor = str_replace(supervisor, "Besufikad Birhanu", "Besufikad"), supervisor = str_replace(supervisor, "Habtamu Ayele", "Habtamu"), 
supervisor = str_replace(supervisor, "Sisay addis", "Sisay"), supervisor = str_replace(supervisor, "Bekalu dibaba", "Bekalu"), 
supervisor = str_replace(supervisor, "Henok Ayele", "Henok"), supervisor = str_replace(supervisor, "Belachew Mamuye", "Belachew"))

df_merge_reg <- inner_join(x = emp_reg_act, y = df_expected, by="supervisor")
#rename sup name
df_merge_reg <- df_merge_reg %>% mutate(supervisor = str_replace(supervisor,"Addis Mengistu", "Addis"), supervisor = str_replace(supervisor, "Asnake Getu", "Asnake"),
supervisor = str_replace(supervisor, "Hiwot Zelalem", "Hiwot"), supervisor = str_replace(supervisor, "Natnael Shewanes", "Natnael"),
supervisor = str_replace(supervisor, "Selamu Bulado", "Selamu"), supervisor = str_replace(supervisor, "Solomon Genore", "Solomon"), 
supervisor = str_replace(supervisor, "Besufikad Birhanu", "Besufikad"), supervisor = str_replace(supervisor, "Habtamu Ayele", "Habtamu"), 
supervisor = str_replace(supervisor, "Sisay addis", "Sisay"), supervisor = str_replace(supervisor, "Bekalu dibaba", "Bekalu"), 
supervisor = str_replace(supervisor, "Henok Ayele", "Henok"), supervisor = str_replace(supervisor, "Belachew Mamuye", "Belachew"))

df_merge_zone <- inner_join(x = emp_zone_act, y = df_expected, by="supervisor")
#rename sup name
df_merge_zone<- df_merge_zone %>% mutate(supervisor = str_replace(supervisor,"Addis Mengistu", "Addis"), supervisor = str_replace(supervisor, "Asnake Getu", "Asnake"),
supervisor = str_replace(supervisor, "Hiwot Zelalem", "Hiwot"), supervisor = str_replace(supervisor, "Natnael Shewanes", "Natnael"),
supervisor = str_replace(supervisor, "Selamu Bulado", "Selamu"), supervisor = str_replace(supervisor, "Solomon Genore", "Solomon"), 
supervisor = str_replace(supervisor, "Besufikad Birhanu", "Besufikad"), supervisor = str_replace(supervisor, "Habtamu Ayele", "Habtamu"), 
supervisor = str_replace(supervisor, "Sisay addis", "Sisay"), supervisor = str_replace(supervisor, "Bekalu dibaba", "Bekalu"), 
supervisor = str_replace(supervisor, "Henok Ayele", "Henok"), supervisor = str_replace(supervisor, "Belachew Mamuye", "Belachew"))

df_merge_woreda <- inner_join(x = emp_woreda_act, y = df_expected, by="supervisor")
#rename sup name
df_merge_woreda <- df_merge_woreda %>% mutate(supervisor = str_replace(supervisor,"Addis Mengistu", "Addis"), supervisor = str_replace(supervisor, "Asnake Getu", "Asnake"),
supervisor = str_replace(supervisor, "Hiwot Zelalem", "Hiwot"), supervisor = str_replace(supervisor, "Natnael Shewanes", "Natnael"),
supervisor = str_replace(supervisor, "Selamu Bulado", "Selamu"), supervisor = str_replace(supervisor, "Solomon Genore", "Solomon"), 
supervisor = str_replace(supervisor, "Besufikad Birhanu", "Besufikad"), supervisor = str_replace(supervisor, "Habtamu Ayele", "Habtamu"), 
supervisor = str_replace(supervisor, "Sisay addis", "Sisay"), supervisor = str_replace(supervisor, "Bekalu dibaba", "Bekalu"), 
supervisor = str_replace(supervisor, "Henok Ayele", "Henok"), supervisor = str_replace(supervisor, "Belachew Mamuye", "Belachew"))

df_merge_client <- inner_join(x = client_act, y = df_expected, by="supervisor")
#rename sup name
df_merge_client<- df_merge_client %>% mutate(supervisor = str_replace(supervisor,"Addis Mengistu", "Addis"), supervisor = str_replace(supervisor, "Asnake Getu", "Asnake"),
supervisor = str_replace(supervisor, "Hiwot Zelalem", "Hiwot"), supervisor = str_replace(supervisor, "Natnael Shewanes", "Natnael"),
supervisor = str_replace(supervisor, "Selamu Bulado", "Selamu"), supervisor = str_replace(supervisor, "Solomon Genore", "Solomon"), 
supervisor = str_replace(supervisor, "Besufikad Birhanu", "Besufikad"), supervisor = str_replace(supervisor, "Habtamu Ayele", "Habtamu"), 
supervisor = str_replace(supervisor, "Sisay addis", "Sisay"), supervisor = str_replace(supervisor, "Bekalu dibaba", "Bekalu"), 
supervisor = str_replace(supervisor, "Henok Ayele", "Henok"), supervisor = str_replace(supervisor, "Belachew Mamuye", "Belachew"))

df_merge_profile <- inner_join(x = profile_act, y = df_expected, by="supervisor")
#rename sup name
df_merge_profile<- df_merge_profile %>% mutate(supervisor = str_replace(supervisor,"Addis Mengistu", "Addis"), supervisor = str_replace(supervisor, "Asnake Getu", "Asnake"),
supervisor = str_replace(supervisor, "Hiwot Zelalem", "Hiwot"), supervisor = str_replace(supervisor, "Natnael Shewanes", "Natnael"),
supervisor = str_replace(supervisor, "Selamu Bulado", "Selamu"), supervisor = str_replace(supervisor, "Solomon Genore", "Solomon"), 
supervisor = str_replace(supervisor, "Besufikad Birhanu", "Besufikad"), supervisor = str_replace(supervisor, "Habtamu Ayele", "Habtamu"), 
supervisor = str_replace(supervisor, "Sisay addis", "Sisay"), supervisor = str_replace(supervisor, "Bekalu dibaba", "Bekalu"), 
supervisor = str_replace(supervisor, "Henok Ayele", "Henok"), supervisor = str_replace(supervisor, "Belachew Mamuye", "Belachew"))


```

Column 
-----------------------------------------------------------------------
### EMPLOYEE FEDERAL LEVEL EXPECTED AND ACTUAL

```{r}

#plot fig
fig2 <- df_merge_fed %>% plot_ly()
fig2 <- fig2 %>% add_trace(x = ~supervisor, y = ~count_fed_emp, type = 'bar',  name = 'Actual data', marker = list(color = '#0AA1DD'))
fig2 <- fig2 %>% add_trace(x = ~supervisor, y = ~emp_fed_exp, type = 'bar', name = 'Expected data', marker = list(color = '#006E7F'))
fig2 <- fig2 %>% layout(xaxis = list(title = 'SUPERVISOR'), barmode = 'group')          
fig2 <- fig2 %>% layout(yaxis = list(title = 'n'), barmode = 'group')

fig2

```

### EMPLOYEE REGIONAL LEVEL EXPECTED AND ACTUAL

```{r}

#plot fig
fig3 <- df_merge_reg  %>% plot_ly()
fig3 <- fig3 %>% add_trace(x = ~supervisor, y = ~count_reg_emp, type = 'bar',  name = 'Actual data', marker = list(color = '#0AA1DD'))
fig3 <- fig3 %>% add_trace(x = ~supervisor, y = ~emp_reg_exp, type = 'bar', name = 'Expected data', marker = list(color = '#006E7F'))
fig3 <- fig3 %>% layout(xaxis = list(title = 'SUPERVISOR'), barmode = 'group')          
fig3 <- fig3 %>% layout(yaxis = list(title = 'n'), barmode = 'group')

fig3

```

### EMPLOYEE ZONAL LEVEL EXPECTED AND ACTUAL

```{r}

#plot fig
fig4 <- df_merge_zone  %>% plot_ly()
fig4 <- fig4 %>% add_trace(x = ~supervisor, y = ~count_zone_emp, type = 'bar',  name = 'Actual data', marker = list(color = '#0AA1DD'))
fig4 <- fig4 %>% add_trace(x = ~supervisor, y = ~emp_zone_exp, type = 'bar', name = 'Expected data', marker = list(color = '#006E7F'))
fig4 <- fig4 %>% layout(xaxis = list(title = 'SUPERVISOR'), barmode = 'group')          
fig4 <- fig4 %>% layout(yaxis = list(title = 'n'), barmode = 'group')

fig4

```

Column 
-----------------------------------------------------------------------
### EMPLOYEE WOREDA LEVEL EXPECTED AND ACTUAL

```{r}

#plot fig
fig5 <- df_merge_woreda %>% plot_ly()
fig5 <- fig5 %>% add_trace(x = ~supervisor, y = ~count_woreda_emp, type = 'bar',  name = 'Actual data', marker = list(color = '#0AA1DD'))
fig5 <- fig5 %>% add_trace(x = ~supervisor, y = ~emp_woreda_exp, type = 'bar', name = 'Expected data', marker = list(color = '#006E7F'))
fig5 <- fig5 %>% layout(xaxis = list(title = 'SUPERVISOR'), barmode = 'group')          
fig5 <- fig5 %>% layout(yaxis = list(title = 'n'), barmode = 'group')

fig5

```

### CLIENT LEVEL EXPECTED AND ACTUAL

```{r}

#plot fig
fig6 <- df_merge_client %>% plot_ly()
fig6 <- fig6 %>% add_trace(x = ~supervisor, y = ~count_client, type = 'bar',  name = 'Actual data', marker = list(color = '#0AA1DD'))
fig6 <- fig6 %>% add_trace(x = ~supervisor, y = ~client_exp, type = 'bar', name = 'Expected data', marker = list(color = '#006E7F'))
fig6 <- fig6 %>% layout(xaxis = list(title = 'SUPERVISOR'), barmode = 'group')          
fig6 <- fig6 %>% layout(yaxis = list(title = 'n'), barmode = 'group')

fig6

```

### PROFILE LEVEL EXPECTED AND ACTUAL

```{r}

#plot fig
fig7 <- df_merge_profile %>% plot_ly()
fig7 <- fig7 %>% add_trace(x = ~supervisor, y = ~count_profile, type = 'bar',  name = 'Actual data', marker = list(color = '#0AA1DD'))
fig7 <- fig7 %>% add_trace(x = ~supervisor, y = ~profile_exp, type = 'bar', name = 'Expected data', marker = list(color = '#006E7F'))
fig7 <- fig7 %>% layout(xaxis = list(title = 'SUPERVISOR'), barmode = 'group')          
fig7 <- fig7 %>% layout(yaxis = list(title = 'n'), barmode = 'group')

fig7

```

ORG. LEVEL
=====================================

Column 
-----------------------------------------------------------------------

### EMPLOYEE DATA BY ORGANIZATION LEVEL
```{r }
employee %>% 
  count(org_level, supervisor) %>%
  hchart('column', hcaes(x = 'supervisor', y = 'n', group = 'org_level'))
```

### CLIENT DATA BY ORGANIZATION LEVEL
```{r client}
client %>% 
  count(org_level, supervisor) %>%
  hchart('column', hcaes(x = 'supervisor', y = 'n', group = 'org_level'))
```

### PROFILE DATA BY ORGANIZATION LEVEL
```{r profile}
profile %>% 
  count(org_level, supervisor) %>%
  hchart('column', hcaes(x = 'supervisor', y = 'n', group = 'org_level'))
```

Column 
-----------------------------------------------------------------------

### EXPECTED TABLE.

```{r }
datatable(expected_table)
```
