---
title: "DRDIP2 Report Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(haven)
library(plyr)
library(tidyverse)
library(dplyr)
library(lubridate)
library(highcharter)
library(plotly)
library(DT)
library(stringr)
library(ggplot2)
library(viridis)
library(hrbrthemes)

```

```{r}
#Import HH Survey Endline Data
hh_endline <- read_dta("C:/Users/Admin/Desktop/Backup/Documents/Survey - Projects/DRDIP II/Download Data/DRDIP_HH_Survey_2022_Endline/SuSo Download/raw/DRDIP_HH_Survey_2022_Endline/DRDIP_HH_Survey_2022_Endline.dta")
hh_endline <- as_factor(hh_endline)
hh_endline$GPS__Timestamp <- as_date(hh_endline$GPS__Timestamp)
hh_endline <- hh_endline %>% dplyr::rename("Date_of_interview" = "GPS__Timestamp")

hh_endline <- hh_endline %>% mutate(supervisor = str_replace(supervisor,"Besufekade Berhanu", "Besu"), supervisor = str_replace(supervisor, "Hussien Eshetu", "Hussien"),
supervisor = str_replace(supervisor, "Henok Kifyalew", "Henok"), supervisor = str_replace(supervisor, "Berhanu Lema", "Berhanu"),
supervisor = str_replace(supervisor, "TsegaZeab Miruts", "TsegaZeab"), supervisor = str_replace(supervisor, "Biniam Fishaye", "Biniam"), 
supervisor = str_replace(supervisor, "Getachew Worku", "Getachew"), supervisor = str_replace(supervisor, "Gashayeneh Deribe", "Gashayeneh"), 
supervisor = str_replace(supervisor, "Kahsay Sibhat", "Kahsay"), supervisor = str_replace(supervisor, "Yohans Belachew", "Yohans"), 
supervisor = str_replace(supervisor, "Asefa Belachew", "Asefa"), supervisor = str_replace(supervisor, "Tigist mamo", "Tigist"), supervisor = str_replace(supervisor, "Ziyad haro mahammed", "Ziyad"))

hh_endline <- hh_endline %>% mutate(region = str_replace(region,"Benishangul-Gumuz", "Benishangul"))

#Import HH Survey Baseline Data
hh_baseline <- read_dta("C:/Users/Admin/Desktop/Backup/Documents/Survey - Projects/DRDIP II/Download Data/DRDIP_HH_Survey_2022_Baseline/SuSo Download/raw/DRDIP_HH_Baseline_2022_r/DRDIP_HH_Baseline_2022_r.dta")
hh_baseline <- as_factor(hh_baseline)
hh_baseline$GPS__Timestamp <- as_date(hh_baseline$GPS__Timestamp)
hh_baseline <- hh_baseline %>% dplyr::rename("Date_of_interview" = "GPS__Timestamp")
 
hh_baseline <- hh_baseline %>% mutate(supervisor = str_replace(supervisor,"Besufekade Berhanu", "Besu"), supervisor = str_replace(supervisor, "Hussien Eshetu","Hussien"),
supervisor = str_replace(supervisor, "Henok Kifyalew", "Henok"), supervisor = str_replace(supervisor, "Berhanu Lema", "Berhanu"),
supervisor = str_replace(supervisor, "TsegaZeab Miruts", "TsegaZeab"), supervisor = str_replace(supervisor, "Biniam Fishaye", "Biniam"), 
supervisor = str_replace(supervisor, "Getachew Worku", "Getachew"), supervisor = str_replace(supervisor, "Gashayeneh Deribe", "Gashayeneh"), 
supervisor = str_replace(supervisor, "Kahsay Sibhat", "Kahsay"), supervisor = str_replace(supervisor, "Yohans Belachew", "Yohans"), 
supervisor = str_replace(supervisor, "Asefa Belachew", "Asefa"), supervisor = str_replace(supervisor, "Tigist mamo", "Tigist"), supervisor = str_replace(supervisor, "Ziyad haro mahammed", "Ziyad"))

hh_baseline <- hh_baseline %>% mutate(region = str_replace(region,"Benishangul-Gumuz", "Benishangul"))

   
#Endline Replacement
hh_repl <- read_dta("C:/Users/Admin/Desktop/Backup/Documents/Survey - Projects/DRDIP II/Download Data/Endline Replacement/SuSo Download/raw/DRDIP_Replacement_HHs/DRDIP_Replacement_HHs.dta")
hh_repl <- as_factor(hh_repl)
hh_repl$GPS__Timestamp <- as_date(hh_repl$GPS__Timestamp)
hh_repl <- hh_repl %>% dplyr::rename("Date_of_interview" = "GPS__Timestamp")

hh_repl <- hh_repl %>% mutate(supervisor = str_replace(supervisor,"Besufekade Berhanu", "Besu"), supervisor = str_replace(supervisor, "Hussien Eshetu", "Hussien"),
supervisor = str_replace(supervisor, "Henok Kifyalew", "Henok"), supervisor = str_replace(supervisor, "Berhanu Lema", "Berhanu"),
supervisor = str_replace(supervisor, "TsegaZeab Miruts", "TsegaZeab"), supervisor = str_replace(supervisor, "Biniam Fishaye", "Biniam"), 
supervisor = str_replace(supervisor, "Getachew Worku", "Getachew"), supervisor = str_replace(supervisor, "Gashayeneh Deribe", "Gashayeneh"), 
supervisor = str_replace(supervisor, "Kahsay Sibhat", "Kahsay"), supervisor = str_replace(supervisor, "Yohans Belachew", "Yohans"), 
supervisor = str_replace(supervisor, "Asefa Belachew", "Asefa"), supervisor = str_replace(supervisor, "Tigist mamo", "Tigist"), supervisor = str_replace(supervisor, "Ziyad haro mahammed", "Ziyad"))

hh_repl <- hh_repl %>% mutate(region = str_replace(region,"Benishangul-Gumuz", "Benishangul"))


#Merge Endline

hh_endline_mrg <- rbind.fill(hh_endline, hh_repl)

```

HOME
=====================================

Row
-----------------------------------------------------------------------

### ENDLINE

```{r}
num_end <- nrow(hh_endline)
valueBox(num_end, icon = "fa-bar-chart")
```

### REPLACEMENT ENDLINE

```{r}
num_repl <- nrow(hh_repl)
valueBox(num_repl, icon = "fa-bar-chart")
```

### BASELINE

```{r}
num_base <- nrow(hh_baseline)
valueBox(num_base, icon = "fa-bar-chart")

```

### LAST UPDATED:  

```{r}
updated_time <- Sys.Date()

valueBox(updated_time,icon = "fa-clock", color = "#006E7F")
```

```{r}
tool_type <- c("HH Endline", "HH Baseline", "Replacement")
synced_tool <- c(num_end, num_base, num_repl)

```

```{r Endline}
Besufekade_end <- hh_endline %>% filter(supervisor=="Besu") %>% nrow()
Hussien_end <- hh_endline %>% filter(supervisor=="Hussien") %>% nrow()
Henok_end <- hh_endline %>% filter(supervisor=="Henok") %>% nrow()
Berhanu_end <- hh_endline %>% filter(supervisor=="Berhanu") %>% nrow()
TsegaZeab_end <- hh_endline %>% filter(supervisor=="TsegaZeab") %>% nrow()
Biniam_end <- hh_endline %>% filter(supervisor=="Biniam") %>% nrow()
Getachew_end <- hh_endline %>% filter(supervisor=="Getachew") %>% nrow()
Gashayeneh_end <- hh_endline %>% filter(supervisor=="Gashayeneh") %>% nrow()
Kahsay_end <- hh_endline %>% filter(supervisor=="Kahsay") %>% nrow()
Yohans_end <- hh_endline %>% filter(supervisor=="Yohans") %>% nrow()
Asefa_end <- hh_endline %>% filter(supervisor=="Asefa") %>% nrow()
Tigist_end <- hh_endline %>% filter(supervisor=="Tigist") %>% nrow()
Ziyad_end <- hh_endline %>% filter(supervisor=="Ziyad") %>% nrow()
```

```{r baseline}
Besufekade_base <- hh_baseline %>% filter(supervisor=="Besu") %>% nrow()
Hussien_base <- hh_baseline %>% filter(supervisor=="Hussien") %>% nrow()
Henok_base <- hh_baseline %>% filter(supervisor=="Henok") %>% nrow()
Berhanu_base <- hh_baseline %>% filter(supervisor=="Berhanu") %>% nrow()
TsegaZeab_base <- hh_baseline %>% filter(supervisor=="TsegaZeab") %>% nrow()
Biniam_base <- hh_baseline %>% filter(supervisor=="Biniam") %>% nrow()
Getachew_base <- hh_baseline %>% filter(supervisor=="Getachew") %>% nrow()
Gashayeneh_base <- hh_baseline %>% filter(supervisor=="Gashayeneh") %>% nrow()
Kahsay_base <- hh_baseline %>% filter(supervisor=="Kahsay") %>% nrow()
Yohans_base <- hh_baseline %>% filter(supervisor=="Yohans") %>% nrow()
Asefa_base <- hh_baseline %>% filter(supervisor=="Asefa") %>% nrow()
Tigist_base <- hh_baseline %>% filter(supervisor=="Tigist") %>% nrow()
Ziyad_base <- hh_baseline %>% filter(supervisor=="Ziyad") %>% nrow()
```

```{r}
endline_by_date <- hh_endline_mrg %>% select('Date_of_interview', 'supervisor')%>% 
  group_by(Date_of_interview, supervisor) %>% dplyr::summarise(count_date = n()) %>%  drop_na() %>% 
  arrange(Date_of_interview)
  
```

Column {.tabset}
-----------------------------------------------------------------------
### BASELINE DAILY PROGRESS BY SUPERVISOR

```{r}
hh_baseline %>% select('Date_of_interview', 'supervisor') %>% 
  arrange(Date_of_interview) %>% 
  dplyr::count( Date_of_interview, supervisor) %>% 
  hchart('spline', hcaes(x = 'Date_of_interview', y = 'n', group = "supervisor"))
```

### ENDLINE DAILY PROGRESS BY SUPERVISOR
```{r}
hh_endline_mrg %>% select('Date_of_interview', 'supervisor') %>% 
  arrange(Date_of_interview) %>% 
  dplyr::count( Date_of_interview,supervisor) %>% 
  hchart('spline', hcaes(x = 'Date_of_interview', y = 'n', group = "supervisor"))

```


Column 
-----------------------------------------------------------------------

### SUPERVISOR BY HOUSEHOLD QUESTIONNAIRE {data-width=400}

```{r}
sup_name <- c("Besufekade", "Hussien", "Henok", "Berhanu", "TsegaZeab", "Biniam", "Getachew", "Gashayeneh", "Kahsay", "Yohans", "Asefa", "Tigist", "Ziyad")
sup_end <- c(Besufekade_end, Hussien_end, Henok_end, Berhanu_end, TsegaZeab_end, Biniam_end, Getachew_end, Gashayeneh_end, Kahsay_end, Yohans_end, Asefa_end, Tigist_end, Ziyad_end)

sup_base <- c(Besufekade_base, Hussien_base, Henok_base, Berhanu_base, TsegaZeab_base, Biniam_base, Getachew_base, Gashayeneh_base, Kahsay_base, Yohans_base, Asefa_base, Tigist_base, Ziyad_base)


data_sup <- data.frame(sup_name, sup_end, sup_base)
data_sup <- data_sup %>% arrange(sup_end)
#to arrange
data_sup$sup_name<- factor(data_sup$sup_name, levels=data_sup[["sup_name"]])

#plot fig
fig1 <- data_sup %>% plot_ly()
fig1 <- fig1 %>% add_trace(x = ~sup_name, y = ~sup_end, type = 'bar',  name = 'Endline', marker = list(color = '#006E7F'))
fig1 <- fig1 %>% add_trace(x = ~sup_name, y = ~sup_base, type = 'bar', name = 'Baseline', marker = list(color = '#79DAE8'))
fig1 <- fig1 %>% layout(xaxis = list(title = 'SUPERVISOR'), barmode = 'group')          
fig1 <- fig1 %>% layout(yaxis = list(title = 'n'), barmode = 'group')

fig1

```

### HH ENDLINE QUESTIONNAIRE  BY REGION {data-width=300}
```{r }
hh_endline %>% 
  dplyr::count(region) %>%
  arrange(-n) %>% 
  hchart('bar', hcaes(x = 'region', y = 'n'), color_stops(n=4, colors = c("#F65A83", "#FF1E00", "#21E1E1", "#224B0C")))
```


### TOTAL SYNCED DATA BY QUESTIONNAIRE TYPE {data-width=300}

```{r}
tool_type <- c("Endline", "Baseline", "Replacement")
synced_tool <- c(num_end, num_base, num_repl)


fig <- plot_ly(type='pie', labels= ~tool_type, values= ~synced_tool,
               textinfo='label+percent',
               insidetextorientation='radial',
               marker = list(colors = c('#006E7F','#9BA3EB','#79DAE8'))
               
               )
fig

```

EXPECTED vs ACTUAL
=====================================
Row
-----------------------------------------------------------------------

### ENDLINE

```{r}
num_end <- nrow(hh_endline)
valueBox(num_end, icon = "fa-bar-chart")
```

### REPLACEMENT ENDLINE

```{r}
num_repl <- nrow(hh_repl)
valueBox(num_repl, icon = "fa-bar-chart")
```

### BASELINE

```{r}
num_base <- nrow(hh_baseline)
valueBox(num_base, icon = "fa-bar-chart")

```

### LAST UPDATED:  

```{r}
updated_time <- Sys.Date()

valueBox(updated_time,icon = "fa-clock", color = "#006E7F")
```

```{r}
tool_type <- c("HH Endline", "HH Baseline", "Replacement")
synced_tool <- c(num_end, num_base, num_repl)

```


```{r endline expected}
supervisor <- c("Besu", "Henok", "Berhanu", "TsegaZeab", "Biniam", "Getachew", "Gashayeneh", "Kahsay", "Yohans", "Asefa", "Tigist", "Ziyad")
Expected <- c(239,	200,	240,	200,	240,	194,	200,	221,	233,	228,	280,	282)
endline_exp_df <- data.frame(supervisor, Expected)

endline_act <- hh_endline_mrg %>% group_by(supervisor) %>% dplyr::summarise(Endline = n()) %>% arrange(Endline)

endline_act$supervisor<- factor(endline_act$supervisor, levels=endline_act[["supervisor"]])

endline_merge_df <- inner_join(x = endline_act, y = endline_exp_df, by="supervisor")
```


Column
-----------------------------------------------------------------------
### ENDLINE (EXPECTED vs ACTUAL) {data-width=600}

```{r}

#plot fig
fig2 <- endline_merge_df %>% plot_ly()
fig2 <- fig2 %>% add_trace(x = ~supervisor, y = ~Endline, type = 'bar',  name = 'Actual synced', marker = list(color = '#006E7F'))
fig2 <- fig2 %>% add_trace(x = ~supervisor, y = ~Expected, type = 'bar', name = 'Expected data', marker = list(color = '#79DAE8'))
fig2 <- fig2 %>% layout(xaxis = list(title = 'SUPERVISOR'), barmode = 'group')          
fig2 <- fig2 %>% layout(yaxis = list(title = 'n'), barmode = 'group')

fig2

```

```{r baseline by enumerator}

# hh_baseline<- hh_baseline%>% mutate(enumerator = str_replace(enumerator,"Hussien Eshetu", "Hussien"), enumerator = str_replace(enumerator, "Yeshalem Amsalu Kasshun", "Yeshalem"),
# enumerator = str_replace(enumerator, "Abrhame Tsgaye", "Abrhame"), enumerator = str_replace(enumerator, "Birara kasay", "Birara"), enumerator = str_replace(enumerator, "Semegn Abebe", "Semegn"),enumerator = str_replace(enumerator, "Sleshi Ketema", "Sleshi"))
#  
# baseline_act <- hh_baseline %>% group_by(enumerator) %>% dplyr::summarise(count_baseline = n()) %>% arrange(count_baseline)
# 
# baseline_act$enumerator<- factor(baseline_act$enumerator, levels=baseline_act[["enumerator"]])

```

```{r refugee and local}

hh_baseline <- hh_baseline %>% mutate(supervisor = str_replace(supervisor,"Besufekade Berhanu", "Besu"), supervisor = str_replace(supervisor, "Hussien Eshetu", "Hussien"),
supervisor = str_replace(supervisor, "Henok Kifyalew", "Henok"), supervisor = str_replace(supervisor, "Berhanu Lema", "Berhanu"),
supervisor = str_replace(supervisor, "TsegaZeab Miruts", "TsegaZeab"), supervisor = str_replace(supervisor, "Biniam Fishaye", "Biniam"), 
supervisor = str_replace(supervisor, "Getachew Worku", "Getachew"), supervisor = str_replace(supervisor, "Gashayeneh Deribe", "Gashayeneh"), 
supervisor = str_replace(supervisor, "Kahsay Sibhat", "Kahsay"), supervisor = str_replace(supervisor, "Yohans Belachew", "Yohans"), 
supervisor = str_replace(supervisor, "Asefa Belachew", "Asefa"), supervisor = str_replace(supervisor, "Tigist mamo", "Tigist"), supervisor = str_replace(supervisor, "Ziyad haro mahammed", "Ziyad"))

refugee <-  hh_baseline %>% select('supervisor', 'A107') %>% filter(A107=="Refugee")%>% 
  group_by(supervisor) %>% summarise(Refugee = n())

local <-  hh_baseline %>% select('supervisor', 'A107') %>% filter(A107=="Local resident")%>% 
  group_by(supervisor) %>% summarise(Local = n())

merged_refg_loc <- inner_join(x = refugee, y = local, by="supervisor")
```


### BASELINE DATA BY REFUGEE AND LOCAL {data-width=500}

```{r}

#plot fig
# fig3 <- baseline_act %>% plot_ly()
# fig3 <- fig3 %>% add_trace(x = ~enumerator, y = ~count_baseline, type = 'bar',  name = 'Synced data', marker = list(color = '#68B984'))
# 
# fig3 <- fig3 %>% layout(xaxis = list(title = 'ENUMERATOR'), barmode = 'group')          
# fig3 <- fig3 %>% layout(yaxis = list(title = 'n'), barmode = 'group')
# 
# fig3
# 
fig5 <- merged_refg_loc %>% plot_ly()
fig5 <- fig5 %>% add_trace(x = ~supervisor, y = ~Refugee, type = 'bar',  name = 'Refugee', marker = list(color = '#FFBF00'))
fig5 <- fig5 %>% add_trace(x = ~supervisor, y = ~Local, type = 'bar', name = 'Local resident', marker = list(color = '#2B3A55'))

fig5 <- fig5 %>% layout(title = "",
         xaxis = list(title = ""),
         yaxis = list(title = 'n'), barmode = 'group')

fig5


```


Column 
-----------------------------------------------------------------------
### ENDLINE (EXPECTED, ACTUAL, REPLACED) {data-width=600}
```{r}
repl_by_sup <- hh_repl %>% select('supervisor') %>% 
  group_by(supervisor) %>% dplyr::summarise(Replaced = n()) %>% drop_na() %>%
  arrange(Replaced)
  
expected_merged <- right_join(x = repl_by_sup, y = endline_merge_df, by="supervisor")  
expected_merged <- replace(expected_merged, is.na(expected_merged), 0)
#plot fig 4

fig4 <- expected_merged %>% plot_ly()
fig4 <- fig4 %>% add_trace(x = ~supervisor, y = ~Replaced, type = 'bar',  name = 'Replaced', marker = list(color = '#0AA1DD'))
fig4 <- fig4 %>% add_trace(x = ~supervisor, y = ~Endline, type = 'bar', name = 'Endline Found', marker = list(color = '#006E7F'))
fig4 <- fig4 %>% add_trace(x = ~supervisor, y = ~Expected, type = 'bar', name = 'Expected', marker = list(color = '#79DAE8'))
fig4 <- fig4 %>% layout(xaxis = list(title = 'SUPERVISOR'), barmode = 'group')          
fig4 <- fig4 %>% layout(yaxis = list(title = 'n'), barmode = 'group')

fig4
```

### TOTAL BASELINE DATA BY SUPERVISOR {data-width=500}
```{r}
# baseline_by_kebele <- hh_baseline %>% select('supervisor','kebele')%>% filter(supervisor=="Hussien") %>% 
#   group_by(kebele) %>% dplyr::summarise(kebele_count = n()) %>%  drop_na() %>% 
#   arrange(kebele_count)
# 
# baseline_by_kebele$kebele<- factor(baseline_by_kebele$kebele, levels=baseline_by_kebele[["kebele"]])
baseline_by_sup <- hh_baseline %>% select ('supervisor') %>% 
  group_by(supervisor) %>% dplyr::summarise(total_baseline = n()) %>% drop_na() %>%
  arrange(total_baseline)

baseline_by_sup$supervisor<- factor(baseline_by_sup$supervisor, levels=baseline_by_sup[["supervisor"]])

```


```{r}

fig5 <- baseline_by_sup %>% plot_ly()
fig5 <- fig5 %>% add_trace(x = ~supervisor, y = ~total_baseline, type = 'bar',  name = 'Synced data', marker = list(color = '#2B3A55'))

fig5 <- fig5 %>% layout(xaxis = list(title = ''), yaxis = list(title = 'n'), barmode = 'coloumn')          


fig5

```

 
KPI
=====================================
Row
-----------------------------------------------------------------------

### ENDLINE

```{r}
num_end <- nrow(hh_endline)
valueBox(num_end, icon = "fa-bar-chart")
```

### REPLACEMENT ENDLINE

```{r}
num_repl <- nrow(hh_repl)
valueBox(num_repl, icon = "fa-bar-chart")
```

### BASELINE

```{r}
num_base <- nrow(hh_baseline)
valueBox(num_base, icon = "fa-bar-chart")

```

### LAST UPDATED:  

```{r}
updated_time <- Sys.Date()

valueBox(updated_time,icon = "fa-clock", color = "#006E7F")
```

Column
-----------------------------------------------------------------------
### {.no-padding data-height=350}
```{r}

hp<-hh_endline_mrg %>% select('region', 'D2') %>% filter(D2=="Yes")%>% 
  group_by(region) %>% summarise(Health_post = n())

  
hc<-hh_endline_mrg %>% select('region', 'D4') %>% filter(D4=="Yes")%>% 
  group_by(region) %>% summarise(Health_center = n())


hosp<-hh_endline_mrg %>% select('region', 'D6') %>% filter(D6=="Yes")%>% 
  group_by(region) %>% summarise(Hospital = n())

HF_1_2 <- inner_join(x = hp, y = hc, by="region")

HF_1_2_3 <- inner_join(x = HF_1_2, y = hosp, by="region")


fig5 <- HF_1_2_3 %>% plot_ly()
fig5 <- fig5 %>% add_trace(x = ~region, y = ~Health_post, type = 'bar',  name = 'Health Post', marker = list(color = '#FFBF00'))
fig5 <- fig5 %>% add_trace(x = ~region, y = ~Health_center, type = 'bar', name = 'Health Center', marker = list(color = '#2B3A55'))
fig5 <- fig5 %>% add_trace(x = ~region, y = ~Hospital, type = 'bar', name = 'Hospital', marker = list(color = '#65647C'))
#fig5 <- fig5 %>% layout(xaxis = list(title = 'Beneficiaries with Access to Health Facilities'), barmode = 'group')          
#fig5 <- fig5 %>% layout(yaxis = list(title = 'n'), barmode = 'group')
fig5 <- fig5 %>% layout(title = "ACCESS TO HEALTH FACILITY",
         xaxis = list(title = ""),
         yaxis = list(title = 'n'), barmode = 'group')

fig5
```

### {.no-padding data-height=350}

```{r}

animal_service<-hh_endline_mrg %>% select(D15) %>% group_by(D15) %>% 
  summarise(count = n()) %>% drop_na() %>% 
  hchart('pie', hcaes(x = D15, y = count, color=c('#5DA7DB','#2B3A55','#FFBF00'))) %>% 
  hc_tooltip(pointFormat='<b>Proportion: </b> {point.percentage:,.2f}%') %>% 
  hc_title(text = 'ACCESS TO ANIMAL HEALTH SERVICES', style = list(fontSize = '12px', fontWeight = 'bold')) 
animal_service
#color =  c('#F57328','#2B3A55','#FFBF00') F57328             
```

Column
-----------------------------------------------------------------------
### {.no-padding data-height=350} 
```{r}

first_cycle<-hh_endline_mrg %>% select('region', 'D29') %>% filter(D29=="Yes")%>% 
  group_by(region) %>% summarise(First_Cycle = n())

  
primary_cycle<-hh_endline_mrg %>% select('region', 'D31') %>% filter(D31=="Yes") %>% 
  group_by(region) %>% summarise(Primary = n())


secondary_cycle<-hh_endline_mrg %>% select('region', 'D33') %>% filter(D33=="Yes")%>% 
  group_by(region) %>% summarise(Secondary = n())

prep<-hh_endline_mrg %>% select('region', 'D35') %>% filter(D35=="Yes")%>% 
  group_by(region) %>% summarise(Preparatory = n())

School_2 <- inner_join(x = first_cycle, y = primary_cycle, by="region")

School_3 <- inner_join(x = School_2, y = secondary_cycle, by="region")

School_4 <- inner_join(x = School_3, y = prep, by="region")

fig6 <- School_4 %>% plot_ly()
fig6 <- fig6 %>% add_trace(x = ~region, y = ~First_Cycle, type = 'bar',  name = 'First Cycle', marker = list(color = '#FFBF00'))
fig6 <- fig6 %>% add_trace(x = ~region, y = ~Primary, type = 'bar', name = 'Primary', marker = list(color = '#2B3A55'))
fig6 <- fig6 %>% add_trace(x = ~region, y = ~Secondary, type = 'bar', name = 'Secondary', marker = list(color = '#65647C'))
fig6 <- fig6 %>% add_trace(x = ~region, y = ~Preparatory, type = 'bar', name = 'Preparatory', marker = list(color = '#F57328'))
#fig5 <- fig5 %>% layout(xaxis = list(title = 'Beneficiaries with Access to Health Facilities'), barmode = 'group')  68B984        
#fig5 <- fig5 %>% layout(yaxis = list(title = 'n'), barmode = 'group')
fig6 <- fig6 %>% layout(title = "ACCESS TO EDUCATION",
         xaxis = list(title = ""),
         yaxis = list(title = 'n'), barmode = 'group')

fig6

```

### {.no-padding data-height=350}

```{r}
water_acces<-hh_endline_mrg %>% select(D48) %>% group_by(D48) %>% 
  summarise(count = n()) %>% drop_na() %>% 
  hchart('pie', hcaes(x = D48, y = count, color=c('#5DA7DB','#2B3A55', '#FFBF00', '#65647C', '#F57328', '#5837D0','#FF6464','#E0144C', '#38E54D'))) %>% 
  hc_tooltip(pointFormat='<b>Proportion: </b> {point.percentage:,.2f}%') %>% 
  hc_title(text = 'MAIN SOURCE OF DRINKING WATER', style = list(fontSize = '12px', fontWeight = 'bold')) 
water_acces
#color=c('#5DA7DB','#FFBF00', '#2B3A55', '#65647C', '#F57328', '#5837D0','#FF6464', '#E0144C','#38E54D' ,'#000000')
#yello #FFBF00
#blue black #2B3A55
```

